import { randomUUID } from 'node:crypto'
import { createClient, type Client } from '@libsql/client'
import { BlockRepository } from '~~/server/repositories/block.repository'
import { hashPassword } from '~~/server/utils/password'
import type { ActivityLevel } from '~~/shared/lib/formulas'
import type { Equipment } from '~~/shared/types/preset.types'
import type { ExperienceLevel, Goal, UnitSystem } from '~~/shared/types/profile.types'

// The DB's user_profiles.gender CHECK constraint allows 'other', but the app-level Gender type
// (shared/lib/formulas.ts) hasn't been widened to match yet -- see the onboarding/DB review notes.
// Typed locally so this seed can still exercise that DB-supported value.
type SeedGender = 'male' | 'female' | 'other'

const url = process.env.TURSO_DATABASE_URL
const authToken = process.env.TURSO_AUTH_TOKEN

if (!url || !authToken) {
  console.error('Missing TURSO_DATABASE_URL or TURSO_AUTH_TOKEN in the environment.')
  process.exit(1)
}

const db = createClient({ url, authToken })

// Base weights (kg) for the exercises used below, roughly a solid intermediate working weight.
// Dummy history is generated by scaling these up over the course of each user's session log.
const BASE_WEIGHTS: Record<string, number> = {
  'Barbell Squat': 60,
  'Barbell Bench Press - Medium Grip': 50,
  'Bent Over Barbell Row': 45,
  'Dumbbell Shoulder Press': 16,
  'Barbell Deadlift': 80,
  'Dumbbell Lunges': 12,
  'Incline Dumbbell Press': 18,
  'Standing Barbell Calf Raise': 60,
  'Romanian Deadlift': 60,
  'Leg Press': 120,
  'Barbell Incline Bench Press - Medium Grip': 45,
  'Wide-Grip Lat Pulldown': 45,
  'Side Lateral Raise': 8,
  'Dumbbell Alternate Bicep Curl': 10,
  'Cable Rope Overhead Triceps Extension': 20,
  'Barbell Hip Thrust': 70,
  'Leg Extensions': 40,
  'Lying Leg Curls': 30,
  'Hammer Curls': 10,
  'EZ-Bar Skullcrusher': 20,
  'Dumbbell Squat': 20,
  'Stiff-Legged Dumbbell Deadlift': 16,
  'Close-Grip Dumbbell Press': 14,
}

interface SplitExerciseSpec {
  name: string
  setType: 'weight_reps' | 'bodyweight_reps'
  targetSets: number
  targetReps: number
  targetRpe: number
}

interface SplitDaySpec {
  name: string
  location: 'gym' | 'home'
  exercises: SplitExerciseSpec[]
}

interface TestUserSpec {
  id: string
  email: string
  displayName: string
  roles: string[]
  gender: SeedGender
  dateOfBirth: string
  heightCm: number
  activityLevel: ActivityLevel
  experienceLevel: ExperienceLevel
  primaryGoal: Goal
  trainingDaysPerWeek: number
  equipment: Equipment
  unitSystem: UnitSystem
  timezone: string
  startWeightKg: number
  targetWeightKg: number
  splitName: string
  days: SplitDaySpec[]
  weeksOfHistory: number
  sessionsPerWeek: number
  endDaysAgo: number // how many days before "today" the generated history stops
  leaveInProgressToday: boolean
}

const wr = (name: string, targetSets: number, targetReps: number, targetRpe: number): SplitExerciseSpec =>
  ({ name, setType: 'weight_reps', targetSets, targetReps, targetRpe })
const bw = (name: string, targetSets: number, targetReps: number, targetRpe: number): SplitExerciseSpec =>
  ({ name, setType: 'bodyweight_reps', targetSets, targetReps, targetRpe })

const TEST_USERS: TestUserSpec[] = [
  {
    id: 'test-user', // matches the hardcoded x-user-id header in app/plugins/api.ts
    email: 'test-user@hadeed.dev',
    displayName: 'Alex Morgan',
    roles: ['member'],
    gender: 'male',
    dateOfBirth: '1996-04-12',
    heightCm: 178,
    activityLevel: 'moderately_active',
    experienceLevel: 'intermediate',
    primaryGoal: 'muscle_gain',
    trainingDaysPerWeek: 4,
    equipment: 'gym',
    unitSystem: 'metric',
    timezone: 'America/New_York',
    startWeightKg: 78,
    targetWeightKg: 84,
    splitName: 'Push Pull Legs (Dummy)',
    weeksOfHistory: 4,
    sessionsPerWeek: 4,
    endDaysAgo: 1,
    leaveInProgressToday: true,
    days: [
      {
        name: 'Push',
        location: 'gym',
        exercises: [
          wr('Barbell Bench Press - Medium Grip', 4, 6, 8),
          wr('Dumbbell Shoulder Press', 3, 10, 7),
          wr('Incline Dumbbell Press', 3, 10, 7),
          wr('Cable Rope Overhead Triceps Extension', 3, 12, 7),
        ],
      },
      {
        name: 'Pull',
        location: 'gym',
        exercises: [
          wr('Bent Over Barbell Row', 4, 8, 8),
          wr('Wide-Grip Lat Pulldown', 3, 10, 7),
          bw('Pullups', 3, 8, 8),
          wr('Hammer Curls', 3, 12, 7),
        ],
      },
      {
        name: 'Legs',
        location: 'gym',
        exercises: [
          wr('Barbell Squat', 4, 6, 8),
          wr('Romanian Deadlift', 3, 8, 8),
          wr('Leg Press', 3, 10, 7),
          wr('Standing Barbell Calf Raise', 4, 15, 7),
        ],
      },
    ],
  },
  {
    id: 'test-user-2',
    email: 'test-user-2@hadeed.dev',
    displayName: 'Sam Rivera',
    roles: ['member'],
    gender: 'female',
    dateOfBirth: '1993-09-02',
    heightCm: 165,
    activityLevel: 'lightly_active',
    experienceLevel: 'beginner',
    primaryGoal: 'fat_loss',
    trainingDaysPerWeek: 2,
    equipment: 'home',
    unitSystem: 'metric',
    timezone: 'Europe/Lisbon',
    startWeightKg: 72,
    targetWeightKg: 63,
    splitName: 'Home Full Body (Dummy)',
    weeksOfHistory: 4,
    sessionsPerWeek: 2,
    endDaysAgo: 2,
    leaveInProgressToday: false,
    days: [
      {
        name: 'Full Body A',
        location: 'home',
        exercises: [
          wr('Dumbbell Lunges', 3, 12, 7),
          wr('Dumbbell Shoulder Press', 3, 10, 7),
          bw('Pullups', 2, 5, 8),
          wr('Dumbbell Alternate Bicep Curl', 3, 12, 7),
        ],
      },
      {
        name: 'Full Body B',
        location: 'home',
        exercises: [
          wr('Dumbbell Squat', 3, 12, 7),
          wr('Stiff-Legged Dumbbell Deadlift', 3, 10, 7),
          wr('Side Lateral Raise', 3, 15, 7),
          wr('Close-Grip Dumbbell Press', 3, 12, 7),
        ],
      },
    ],
  },
  {
    id: 'test-user-3',
    email: 'test-user-3@hadeed.dev',
    displayName: 'Jordan Blake',
    roles: ['member', 'admin'],
    gender: 'other',
    dateOfBirth: '1988-01-20',
    heightCm: 180,
    activityLevel: 'very_active',
    experienceLevel: 'advanced',
    primaryGoal: 'general_fitness',
    trainingDaysPerWeek: 5,
    equipment: 'both',
    unitSystem: 'imperial',
    timezone: 'Asia/Tokyo',
    startWeightKg: 82,
    targetWeightKg: 80,
    splitName: 'Upper/Lower (Dummy)',
    weeksOfHistory: 4,
    sessionsPerWeek: 5,
    endDaysAgo: 1,
    leaveInProgressToday: false,
    days: [
      {
        name: 'Upper A',
        location: 'gym',
        exercises: [
          wr('Barbell Bench Press - Medium Grip', 4, 6, 8),
          wr('Bent Over Barbell Row', 4, 8, 8),
          wr('Dumbbell Shoulder Press', 3, 10, 7),
          wr('Hammer Curls', 3, 12, 7),
          wr('EZ-Bar Skullcrusher', 3, 12, 7),
        ],
      },
      {
        name: 'Lower A',
        location: 'gym',
        exercises: [
          wr('Barbell Squat', 4, 6, 8),
          wr('Romanian Deadlift', 3, 8, 8),
          wr('Leg Press', 3, 10, 7),
          wr('Standing Barbell Calf Raise', 4, 15, 7),
        ],
      },
      {
        name: 'Upper B',
        location: 'gym',
        exercises: [
          wr('Barbell Incline Bench Press - Medium Grip', 4, 8, 8),
          wr('Wide-Grip Lat Pulldown', 4, 10, 8),
          wr('Side Lateral Raise', 3, 15, 7),
          wr('Dumbbell Alternate Bicep Curl', 3, 12, 7),
        ],
      },
      {
        name: 'Lower B',
        location: 'gym',
        exercises: [
          wr('Barbell Hip Thrust', 4, 10, 8),
          wr('Leg Extensions', 3, 12, 7),
          wr('Lying Leg Curls', 3, 12, 7),
          wr('Standing Barbell Calf Raise', 4, 15, 7),
        ],
      },
    ],
  },
]

function addDays(date: Date, days: number): Date {
  return new Date(date.getTime() + days * 24 * 60 * 60 * 1000)
}

function sqliteDatetime(date: Date): string {
  return date.toISOString().slice(0, 19).replace('T', ' ')
}

function sqliteDate(date: Date): string {
  return date.toISOString().slice(0, 10)
}

function round1(n: number): number {
  return Math.round(n * 10) / 10
}

function progressedWeight(base: number, sessionIndex: number, totalSessions: number): number {
  const growth = 1 + 0.15 * (sessionIndex / Math.max(totalSessions - 1, 1))
  return Math.round((base * growth) / 1.25) * 1.25
}

async function findExerciseId(name: string): Promise<string> {
  const result = await db.execute({ sql: 'SELECT id FROM exercises WHERE name = ? LIMIT 1', args: [name] })
  const id = result.rows[0]?.id as string | undefined
  if (!id) throw new Error(`Seed: expected exercise "${name}" to exist. Run "npm run db:seed" first.`)
  return id
}

async function findRoleId(key: string): Promise<number> {
  const result = await db.execute({ sql: 'SELECT id FROM roles WHERE key = ? LIMIT 1', args: [key] })
  const id = result.rows[0]?.id as number | undefined
  if (!id) throw new Error(`Seed: expected role "${key}" to exist. Run "npm run db:seed" first.`)
  return id
}

async function findAchievementId(key: string): Promise<number> {
  const result = await db.execute({ sql: 'SELECT id FROM achievements WHERE key = ? LIMIT 1', args: [key] })
  const id = result.rows[0]?.id as number | undefined
  if (!id) throw new Error(`Seed: expected achievement "${key}" to exist. Run "npm run db:seed" first.`)
  return id
}

function generateSessionDates(spec: TestUserSpec, now: Date): Date[] {
  const end = addDays(now, -spec.endDaysAgo)
  const start = addDays(end, -spec.weeksOfHistory * 7)
  const intervalDays = 7 / spec.sessionsPerWeek
  const dates: Date[] = []
  for (let cursor = new Date(start); cursor <= end; cursor = addDays(cursor, intervalDays)) {
    dates.push(new Date(cursor))
  }
  return dates
}

async function seedUser(spec: TestUserSpec, now: Date, dummyPasswordHash: string): Promise<void> {
  await db.execute({
    sql: 'INSERT INTO users (id, email, display_name, password_hash) VALUES (?, ?, ?, ?) ON CONFLICT (id) DO UPDATE SET email = excluded.email, display_name = excluded.display_name, password_hash = excluded.password_hash',
    args: [spec.id, spec.email, spec.displayName, dummyPasswordHash],
  })

  for (const roleKey of spec.roles) {
    const roleId = await findRoleId(roleKey)
    await db.execute({
      sql: 'INSERT OR IGNORE INTO user_roles (user_id, role_id) VALUES (?, ?)',
      args: [spec.id, roleId],
    })
  }

  await db.execute({
    sql: `INSERT INTO user_profiles
            (user_id, date_of_birth, gender, height_cm, activity_level, experience_level, primary_goal,
             training_days_per_week, equipment, unit_system, timezone, updated_at)
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
          ON CONFLICT (user_id) DO UPDATE SET
            date_of_birth = excluded.date_of_birth, gender = excluded.gender, height_cm = excluded.height_cm,
            activity_level = excluded.activity_level, experience_level = excluded.experience_level,
            primary_goal = excluded.primary_goal, training_days_per_week = excluded.training_days_per_week,
            equipment = excluded.equipment, unit_system = excluded.unit_system, timezone = excluded.timezone,
            updated_at = datetime('now')`,
    args: [
      spec.id, spec.dateOfBirth, spec.gender, spec.heightCm, spec.activityLevel, spec.experienceLevel,
      spec.primaryGoal, spec.trainingDaysPerWeek, spec.equipment, spec.unitSystem, spec.timezone,
    ],
  })

  const existingSessions = await db.execute({ sql: 'SELECT COUNT(*) as count FROM workout_sessions WHERE user_id = ?', args: [spec.id] })
  if (((existingSessions.rows[0]?.count as number) ?? 0) > 0) {
    console.log(`  ${spec.id}: history already seeded, skipping body metrics / block / sessions.`)
    return
  }

  console.log(`  ${spec.id}: seeding body metrics, target, split, and session history...`)

  // Body metrics: one entry per week across the history window, trending toward the target.
  const metricStart = addDays(now, -(spec.weeksOfHistory * 7))
  const weeklyDates: Date[] = []
  for (let cursor = new Date(metricStart); cursor <= now; cursor = addDays(cursor, 7)) weeklyDates.push(new Date(cursor))

  let firstMetricDate = ''
  let firstMetricWeight = spec.startWeightKg
  for (const [i, date] of weeklyDates.entries()) {
    const progress = i / Math.max(weeklyDates.length - 1, 1)
    const weight = round1(spec.startWeightKg + (spec.targetWeightKg - spec.startWeightKg) * progress * 0.6 + (Math.random() - 0.5) * 0.6)
    const result = await db.execute({
      sql: `INSERT INTO body_metrics (user_id, recorded_at, weight_kg, body_fat_pct, source)
            VALUES (?, ?, ?, ?, 'manual') RETURNING id`,
      args: [spec.id, sqliteDate(date), weight, i % 3 === 0 ? round1(18 + Math.random() * 8) : null],
    })
    const id = result.rows[0]?.id as number
    if (i === 0) {
      firstMetricDate = sqliteDate(date)
      firstMetricWeight = weight
    }
    if (i === weeklyDates.length - 1) {
      await db.execute({
        sql: 'INSERT INTO body_metric_measurements (body_metric_id, key, value_cm) VALUES (?, ?, ?)',
        args: [id, 'waist', round1(80 + Math.random() * 10)],
      })
    }
  }

  // Active weight target, referencing the earliest body metric as the starting point.
  await db.execute({
    sql: `INSERT INTO user_targets (user_id, metric, target_value, target_date, starting_value, starting_recorded_at, is_active)
          VALUES (?, 'weight', ?, ?, ?, ?, 1)`,
    args: [spec.id, spec.targetWeightKg, sqliteDate(addDays(now, 84)), firstMetricWeight, firstMetricDate || sqliteDate(metricStart)],
  })

  // Program / block / split days / split exercises.
  const blockRepo = new BlockRepository(db)
  const days = await Promise.all(spec.days.map(async (day) => {
    const exercises = await Promise.all(day.exercises.map(async (ex, position) => ({
      exerciseId: await findExerciseId(ex.name),
      position,
      setType: ex.setType,
      targetSets: ex.targetSets,
      targetReps: ex.targetReps,
      targetRpe: ex.targetRpe,
    })))
    return { name: day.name, dayOfWeek: 0, location: day.location, exercises }
  }))
  const dayOfWeekIndexed = days.map((day, i) => ({ ...day, dayOfWeek: i }))

  const block = await blockRepo.createWithDays(spec.id, {
    programId: null,
    name: spec.splitName,
    startDate: sqliteDate(metricStart),
    endDate: null,
    trainingDayMacroTarget: null,
    restDayMacroTarget: null,
    days: dayOfWeekIndexed,
  })
  const blockWithDays = await blockRepo.findWithDays(block.id)
  if (!blockWithDays) throw new Error('Seed: failed to load freshly created block')

  // Workout session history: completed sessions with exercise/set logs, weights progressing over time.
  const sessionDates = generateSessionDates(spec, now)
  let lastCompletedDate: Date | undefined
  let prCount = 0

  for (const [sessionIndex, sessionDate] of sessionDates.entries()) {
    const isLast = sessionIndex === sessionDates.length - 1
    const inProgress = spec.leaveInProgressToday && isLast
    const splitDay = blockWithDays.days[sessionIndex % blockWithDays.days.length]!
    const sessionId = randomUUID()
    // The in-progress "today" session uses `now` directly rather than the last cadence-generated
    // date (which is `endDaysAgo` days back) -- it represents a workout started right now.
    const startedAt = inProgress ? new Date(now) : new Date(sessionDate)
    if (!inProgress) startedAt.setHours(17, 30, 0, 0)
    const completedAt = inProgress ? null : addDays(startedAt, 0)
    if (completedAt) completedAt.setMinutes(completedAt.getMinutes() + 55)

    await db.execute({
      sql: `INSERT INTO workout_sessions (id, user_id, split_day_id, status, started_at, completed_at, version)
            VALUES (?, ?, ?, ?, ?, ?, 1)`,
      args: [sessionId, spec.id, splitDay.id, inProgress ? 'in_progress' : 'completed', sqliteDatetime(startedAt), completedAt ? sqliteDatetime(completedAt) : null],
    })

    const exercisesForSession = inProgress ? splitDay.exercises.slice(0, 1) : splitDay.exercises
    let setLoggedAt = new Date(startedAt)
    let prSetLogId: string | undefined

    for (const [exPosition, splitExercise] of exercisesForSession.entries()) {
      const exerciseLogId = randomUUID()
      await db.execute({
        sql: `INSERT INTO exercise_logs (id, session_id, exercise_id, split_exercise_id, position, set_type, target_sets, target_reps, target_rpe)
              VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        args: [
          exerciseLogId, sessionId, splitExercise.exerciseId, splitExercise.id, exPosition,
          splitExercise.setType, splitExercise.targetSets, splitExercise.targetReps, splitExercise.targetRpe,
        ],
      })

      const exerciseName = spec.days[sessionIndex % spec.days.length]!.exercises[exPosition]!.name
      const base = BASE_WEIGHTS[exerciseName]
      const setCount = inProgress ? Math.min(splitExercise.targetSets ?? 3, 2) : (splitExercise.targetSets ?? 3)

      for (let setNumber = 1; setNumber <= setCount; setNumber++) {
        setLoggedAt = addDays(setLoggedAt, 0)
        setLoggedAt.setMinutes(setLoggedAt.getMinutes() + 3)
        const weightKg = splitExercise.setType === 'weight_reps' && base !== undefined
          ? progressedWeight(base, sessionIndex, sessionDates.length)
          : null
        const reps = (splitExercise.targetReps ?? 8) - (Math.random() < 0.2 ? 1 : 0)
        const rpe = round1((splitExercise.targetRpe ?? 7) + (Math.random() - 0.5))
        const setLogId = randomUUID()
        await db.execute({
          sql: `INSERT INTO set_logs (id, exercise_log_id, set_number, weight_kg, reps, rpe, logged_at, version)
                VALUES (?, ?, ?, ?, ?, ?, ?, 1)`,
          args: [setLogId, exerciseLogId, setNumber, weightKg, reps, rpe, sqliteDatetime(setLoggedAt)],
        })
        if (!inProgress && weightKg !== null && setNumber === setCount && sessionIndex === sessionDates.length - 2) {
          prSetLogId = setLogId
        }
      }
    }

    if (!inProgress) {
      lastCompletedDate = sessionDate
      await db.execute({
        sql: `INSERT INTO xp_ledger (user_id, amount, source_type, source_id) VALUES (?, 50, 'session_completed', ?) ON CONFLICT DO NOTHING`,
        args: [spec.id, sessionId],
      })
      if (prSetLogId && prCount === 0) {
        prCount++
        await db.execute({
          sql: `INSERT INTO xp_ledger (user_id, amount, source_type, source_id) VALUES (?, 25, 'pr', ?) ON CONFLICT DO NOTHING`,
          args: [spec.id, prSetLogId],
        })
      }
    }
  }

  // Streak + achievements reflecting the generated history.
  const currentStreak = Math.min(sessionDates.length, spec.sessionsPerWeek >= 5 ? 9 : spec.sessionsPerWeek >= 4 ? 5 : 3)
  const longestStreak = currentStreak + 2
  await db.execute({
    sql: `INSERT INTO streaks (user_id, current_streak, longest_streak, last_active_date)
          VALUES (?, ?, ?, ?)
          ON CONFLICT (user_id) DO UPDATE SET current_streak = excluded.current_streak, longest_streak = excluded.longest_streak, last_active_date = excluded.last_active_date`,
    args: [spec.id, currentStreak, longestStreak, lastCompletedDate ? sqliteDate(lastCompletedDate) : null],
  })

  const firstSessionAchievementId = await findAchievementId('first_session')
  await db.execute({
    sql: 'INSERT OR IGNORE INTO user_achievements (user_id, achievement_id) VALUES (?, ?)',
    args: [spec.id, firstSessionAchievementId],
  })
  if (prCount > 0) {
    const prAchievementId = await findAchievementId('first_pr')
    await db.execute({
      sql: 'INSERT OR IGNORE INTO user_achievements (user_id, achievement_id) VALUES (?, ?)',
      args: [spec.id, prAchievementId],
    })
  }
  if (currentStreak >= 7) {
    const weekStreakAchievementId = await findAchievementId('week_streak')
    await db.execute({
      sql: 'INSERT OR IGNORE INTO user_achievements (user_id, achievement_id) VALUES (?, ?)',
      args: [spec.id, weekStreakAchievementId],
    })
  }
}

async function seedEmptyUser(db: Client, dummyPasswordHash: string): Promise<void> {
  await db.execute({
    sql: 'INSERT INTO users (id, email, display_name, password_hash) VALUES (?, ?, ?, ?) ON CONFLICT (id) DO UPDATE SET email = excluded.email, password_hash = excluded.password_hash',
    args: ['test-user-empty', 'test-user-empty@hadeed.dev', null, dummyPasswordHash],
  })
  const roleId = await findRoleId('member')
  await db.execute({
    sql: 'INSERT OR IGNORE INTO user_roles (user_id, role_id) VALUES (?, ?)',
    args: ['test-user-empty', roleId],
  })
}

async function main() {
  const catalogCheck = await db.execute('SELECT COUNT(*) as count FROM exercises')
  if (((catalogCheck.rows[0]?.count as number) ?? 0) === 0) {
    console.error('Exercise catalog is empty. Run "npm run db:seed" first, then re-run this script.')
    process.exit(1)
  }

  const DUMMY_PASSWORD = 'password123'
  const dummyPasswordHash = await hashPassword(DUMMY_PASSWORD)

  const now = new Date()
  console.log('Seeding dummy users...')
  for (const spec of TEST_USERS) {
    console.log(`- ${spec.id} (${spec.displayName})`)
    await seedUser(spec, now, dummyPasswordHash)
  }

  console.log('- test-user-empty (no profile, for testing onboarding/empty states)')
  await seedEmptyUser(db, dummyPasswordHash)

  console.log('Done. Seeded users: ' + [...TEST_USERS.map(u => u.id), 'test-user-empty'].join(', '))
  console.log('The frontend dev header (app/plugins/api.ts) always sends x-user-id: test-user,')
  console.log('so that account is the one you will see when using the app itself.')
  console.log('Use the others via curl/Postman with a custom x-user-id header, e.g.:')
  console.log('  curl -H "x-user-id: test-user-3" http://localhost:3000/api/profile')
  console.log(`All seeded users share the password: ${DUMMY_PASSWORD}`)
  console.log('Log in at /login with e.g. test-user@hadeed.dev / ' + DUMMY_PASSWORD)
}

main()
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
  .finally(() => db.close())
